version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - g++
    - cmake
    - libhdf5-dev
    - libpng-dev

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
