[build-system]
requires = [
    "setuptools>=65.6.3",
    "wheel",
    "numpy<1.22",
    "cython",
    "scikit-build>=0.16.3",
    "cmake>=3.10.0",
    "ninja",
    "setuptools_scm[toml]>=7.0.5",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel.macos]
skip = ["cp36-*"]
before-all = "brew install homebrew/core/hdf5"

[tool.cibuildwheel.linux]
skip = ["cp36-*"]
manylinux-x86_64-image = "ghcr.io/h5py/manylinux2014_x86_64-hdf5"
