[build-system]
requires = [
    "setuptools >= 46.4.0",
    "wheel",
    "numpy<1.22",
    "cython",
    "setuptools_scm[toml] >= 6.3.1",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "openmc/_version.py"
