[build-system]
requires = ["setuptools", "wheel", "numpy", "cython"]

[tool.cibuildwheel]
build = "cp311-manylinux_x86_64"
manylinux-x86_64-image= "manylinux_2_28"

[tool.cibuildwheel.linux]
before-build = "bash build-deps.sh"
