[build-system]
requires = [
    "setuptools>=65.5.0",
    "wheel",
    "numpy<1.22",
    "cython",
    "scikit-build>=0.16.1",
    "cmake>=3.10.0",
    "ninja",
    "setuptools_scm[toml]>=7.0.5"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel.macos]
skip = ["cp36-*"]

[tool.cibuildwheel.linux]
skip = ["cp36-*"]
