[build-system]
requires = ["setuptools", "wheel", "numpy<1.22", "cython"]

[project]
name = "openmc"
dynamic = ["version"]
authors = [
  { name="The OpenMC Development Team", email="openmc@anl.gov" },
]
license = {file = "LICENSE"}
description= "OpenMC"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
requires-python = ">=3.7"
dependencies= [
    "numpy>=1.9", "h5py", "scipy", "ipython", "matplotlib",
    "pandas", "lxml", "uncertainties"
]

[project.optional-dependencies]
depletion-mpi = ["depletion-mpi"]
docs = ["sphinx", "sphinxcontrib-katex", "sphinx-numfig", "jupyter",
        "sphinxcontrib-svg2pdfconverter", "sphinx-rtd-theme"]
tests = [
    "pytest",
    "pytest-cov",
    "colorama"
]
vtk= ["vtk"]


[project.urls]
"Homepage" = "https://docs.openmc.org"
"Bug Tracker" = "https://github.com/openmc-dev/openmc//issues"
"Documentation" = "https://readthedocs.org/projects/openmc/"
"Source Code" = "https://github.com/openmc-dev/openmc"

[tool.setuptools.packages.find]
where = ["src/openmc"]