name: Python Format Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Lint code
        run: |
          black openmc/arithmetic.py
